### PR TITLE
Glutin version v0.29.0

### PR DESCRIPTION
**Pull request by kchibisov**

### CODE REVIEW

**Review by maroider — APPROVED** [review]

**Review by MarijnS95 — APPROVED** [review]

**Comment by kchibisov** [comment]
Will wait here until winit min rust version gets resolved, so I can reference the patched winit instead.

**Comment by MarijnS95** [comment]
Let's link to it for tracking purposes: #2400

**Comment by emilk** [comment]
https://github.com/rust-windowing/winit/pull/2400 is merged!

**Comment by kchibisov** [comment]
We're now waiting on https://github.com/rust-windowing/winit/issues/2402 to be resolved or at least reproduced.

**Pull request merged**
