### PR TITLE
[0.21] Fix VSync not being disabled when requested

### PR DESCRIPTION
**Pull request by 2xsaiko**
By default, the swap interval is set to 1 (see below). Since glutin does nothing when vsync=false, this value never gets set to 0, and vsync is enabled by default regardless of the value set.

The problem occurs because of the environment variable vblank_mode. When it is unset, it defaults to 2, which causes the swap interval to default to 1.

Currently, this can be worked around by starting the application with vblank_mode=1 (default swap interval to 0) or vblank_mode=0 (force swap interval to 0).

This patch causes glutin to always set the swap interval.

See #926

### CODE REVIEW

**Comment by goddessfreya** [comment]
Is there a reason this change is not being done against master?

**Comment by 2xsaiko** [comment]
Yeah, I'm using glium which uses 0.21, so that's what I had to use to test. Patch should work the same for master though, I'll rebase it in a sec.

**Comment by 2xsaiko** [comment]
I've opened a new PR in addition to this one for master.

**Comment by goddessfreya** [comment]
Hey @2xsaiko, I just remembered I forgot to publish 0.21.3. Unfortunately, we've switched from Travis CI to Github actions. Can you open a PR that adds [this file](https://github.com/rust-windowing/glutin/blob/master/.github/workflows/publish.yml#L5) to the `backport21` branch, while changing [this line](https://github.com/rust-windowing/glutin/blob/master/.github/workflows/publish.yml#L5) to include the branch name? Can you also bump glutin's version in the `Cargo.toml` too? Thanks.

**Pull request merged**
