### PR TITLE
examples: Exit when the user presses `Escape`

### PR DESCRIPTION
**Pull request by MarijnS95**

### CODE REVIEW

**Comment by kchibisov** [comment]
Hm, maybe set it in title as well, since I think it's only relevant on stacking wms where user doesn't know the hotkey to close a window.

**Comment by MarijnS95** [comment]
You mean the window title? Or enable the close button in the window?

I won't see those because I don't use window borders/decorations in `sway`.

**Comment by kchibisov** [comment]
>You mean the window title?

Yes, window title.

>I won't see those because I don't use window borders/decorations in sway.

You should know how to close any window on sway with the hotkey though.

**Comment by MarijnS95** [comment]
> You should know how to close any window on sway with the hotkey though.

Sure, but I've grown accustomed to graphics (test) apps supporting <kbd>Escape</kbd> specifically.

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
