### PR TITLE
Update contact links

### PR DESCRIPTION
**Pull request by maroider**
- ~~Tested on all platforms changed~~
- ~~Compilation warnings were addressed~~
- ~~`cargo fmt` has been run on this branch~~
- ~~`cargo doc` builds successfully~~
- ~~Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~~
- ~~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~~
- ~~Created or updated an example program if it would help users understand this functionality~~

See rust-windowing/winit#1966

### CODE REVIEW

**Comment by maroider** [comment]
It was suggested that we may want separate rooms/channels for winit and glutin.

I don't really have any strong feelings one way or the other.

**Comment by chrisduerr** [comment]
> It was suggested that we may want separate rooms/channels for winit and glutin.
>
> I don't really have any strong feelings one way or the other.

Honestly with the amount of activity it's probably easier to just keep them combined. The naming itself might be a bit discouraging but people will figure it out.

**Comment by kchibisov** [comment]
>It was suggested that we may want separate rooms/channels for winit and glutin.

There's no reason to do so, glutin isn't a separated project to be fair, since it reexports winit and exposes it in its public API to some point. But that doesn't really matter, all rust-windowing projects should be discussed in one channel for now due to low number of community members. Could rename '#winit' to '#rust-windowing'.

**Review by madsmtm — APPROVED** [review]
I think I suggested the separate channels, but I agree that we should keep them together.

These links are to the `#rust-windowing` "room", so I think we can safely merge this PR whether or not we should rename the `#winit` channel.

**Pull request merged**
