### PR TITLE
README: switch link to new Matrix room

### PR DESCRIPTION
**Pull request by Be-ing**
- [N/A] Tested on all platforms changed
- [N/A] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [N/A] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [N/A] Created or updated an example program if it would help users understand this functionality

### CODE REVIEW

**Comment by kchibisov** [comment]
I'm not entirely sure wrt that. The thing is that the current link is also correct, it's a link to the room where you can go to `#winit`. Before we also had `#glutin`. Though maybe it's fine to point to `#winit` directly.

**Comment by i509VCB** [comment]
Maybe linking to the rust-windowing matrix space would be more apt?

**Comment by kchibisov** [comment]
I'm not familiar with any of that tbf, my link is the one with `irc` in it :p . But whatever works better for matrix folks here.

**Comment by Be-ing** [comment]
The rust-windowing Matrix room's message says it is abandoned and redirects to the winit room.

**Comment by kchibisov** [comment]
I mean that I've clicked on the link in element and it showed glutin room(archived) and winit room.

**Comment by i509VCB** [comment]
I believe the space link is https://matrix.to/#/#rust-windowing:matrix.org

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
