### PR TITLE
Use get_instance_handle() over GetModuleHandle(NULL)

### LINKED ISSUE #1445: ERROR_CLASS_DOES_NOT_EXIST opening window from DLL
Building a glutin context compiled as a dynamically loaded DLL causes:

```plaintext
OsError("GetClassInfoExW function failed: <localized message> (os error 1411)")
```

This error is caused by the `GetModuleHandleW(std::ptr::null())` usage in `glutin/src/api/wgl/mod.rs`, the function returns the handle for the executable, not the DLL.

A similar bug was fixed in winit, see [winit/2301](https://github.com/rust-windowing/winit/pull/2301)

### PR DESCRIPTION
**Pull request by SamRodri**
See the [winit](https://github.com/rust-windowing/winit/pull/2301) discussion about this fix.

fixes #1445

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

### CODE REVIEW

**Comment by SamRodri** [comment]
I see  that there is a major rewrite underway, maybe @kchibisov can copy this patch into his pull request?

**Comment by kchibisov** [comment]
Actually, I don't think I need this patch at all on my branch. I just need to use `hinstance` from the handle instead of that.

I'm not sure how I feel about adding this patch right now given that I'm unlikely to make a glutin release.

Is there a strong need for this patch?

**Comment by SamRodri** [comment]
No rush on my part, I can depend on my fork until your update is released.

**Comment by kchibisov** [comment]
Handled in #1439.

**Pull request closed without merging**
