### PR TITLE
egl: remove cfg from code not needing them

### PR DESCRIPTION
**Pull request by kchibisov**
--

@MarijnS95 I think something like that?

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]

**Comment by MarijnS95** [comment]
I also wonder if we need optimizations like:

https://github.com/rust-windowing/glutin/blob/5a7783c3290a498a17a23030d0aa814bb9febd55/glutin/src/api/egl/config.rs#L330-L347

This should compile down to `match ...? { _ => None }` which can only ever return `None` anyway.

**Comment by kchibisov** [comment]
that's to avoid clippy lints and is easier to read.

**Comment by MarijnS95** [comment]
Didn't we typically disable that lint because this "single match arm" occurs in many more places in `glutin`?

I don't find the (negated) `cfg`s particularly easy to read nor modify when new variants ever need to be added.

**Comment by kchibisov** [comment]
We don't display it and it's never triggered., you can grep for it

**Comment by kchibisov** [comment]
Seems like clippy doesn't complain about it, so I guess it's fine.

**Review by MarijnS95 — APPROVED** [review]

**Pull request merged**
