### PR TITLE
Update parking_lot to 0.8 and wayland-client to 0.23

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by atouchet** [comment]
This should probably be updated in winit as well.

**Comment by Eijebong** [comment]
Fun, I didn't see any dupe when I updated them here... I'll open a PR in winit, thanks

**Comment by Eijebong** [comment]
> error: aborting due to 59 previous errors

Might be a while though :laughing:

**Comment by vberger** [comment]
The update of wayland-client will come with eventloop-2.0.

**Comment by Eijebong** [comment]
:+1: Oh ok, will not lose my time with it then, thanks !

**Comment by Eijebong** [comment]
Should I remove the bump from that PR then ?

**Comment by ZeGentzy** [comment]
Glutin master is now based against eventloop-2.0, so this is fine :)

**Comment by Eijebong** [comment]
Oohh so that's why I didn't see any dupes, there weren't any :p

**Pull request merged**
