### PR TITLE
fix duplicate definition with features egl AND (x11 XOR wayland)

### PR DESCRIPTION
**Pull request by autumnontape**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [n/a] ~~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~~
- [n/a] ~~Created or updated an example program if it would help users understand this functionality~~

I love the rewritten glutin, thank you for the work you put into it!

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]

**Comment by kchibisov** [comment]
@autumnontape would you mind adding a CI job for that? I'm surprised that it wasn't covered... I'd assume it resulted in compilation error.

**Comment by autumnontape** [comment]
@kchibisov I can do that. Should I add both an `egl,wayland` and an `egl,x11` job?

**Comment by autumnontape** [comment]
I went ahead and added both jobs.

**Review by kchibisov — APPROVED** [review]

**Comment by kchibisov** [comment]
Thanks.

**Comment by kchibisov** [comment]
@autumnontape glutin 0.30.2 with your patch was released.

**Pull request merged**
