### PR TITLE
Initial kmsdrm support

### PR DESCRIPTION
**Pull request by StratusFearMe21**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality

(Warning, this PR lists my PR to winit as a dependency)

See [my PR to winit](https://github.com/rust-windowing/winit/pull/2272)

### CODE REVIEW

**Comment by StratusFearMe21** [comment]
Okay, the performance issue is fixed, this PR is ready to be reviewed.

**Comment by StratusFearMe21** [comment]
I'm pretty confident with this PR at this point. As a functionality test, I ported Alacritty to this PR and now it runs straight from the tty https://github.com/StratusFearMe21/alacritty

**Comment by StratusFearMe21** [comment]
The only thing I can think of to add is a cursor, but it's not a must

**Comment by StratusFearMe21** [comment]
Yeah, at this point, I think this is ready to be merged. Im very happy with this PR in its current state.

**Comment by madsmtm** [comment]
FYI: I think https://github.com/rust-windowing/glutin/pull/1435 is going to hit first

**Comment by kchibisov** [comment]
Given that #1439 got merged you'd need to update it, however EGL can create context from DRM device, not sure what needs here?

**Comment by kchibisov** [comment]
I'll close it, since I don't understand what else is required for KMS. I was able to use `glutin` with `gbm` in the context of smithay just fine to draw my triangle. Maybe `vsync` handling needs a bit special treatment, but it could be done separately.

**Pull request closed without merging**
