### PR TITLE
Make display, surface and context creation safe

### PR DESCRIPTION
**Pull request by notgull**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

Uses rust-windowing/raw-window-handle#116 to make display, surface and context creation safe.

I want to get a good idea of what this kind of API would look like. I want to test out the new safe window handles before they're released onto the world.

### CODE REVIEW

**Comment by notgull** [comment]
Hmm, looks like this model kind of breaks `glutin-winit`. Right now, an `&EventLoopWindowTarget` is used to provide the display handle for creating the `Display`. However, since the reference to the ELWT will disappear for event handling, this can't be used as a persistent handle for the display.

A solution would be to use an `&Window` or an `Rc<Window>` instead, but the `Display` initialization generally happens before the `Window` is created. Maybe we could add a type to `winit` similar to `EventLoopWindowTarget` that doesn't disappear during event handling?

**Comment by notgull** [comment]
Rebased around rust-windowing/raw-window-handle#125, aka `raw-window-handle` v0.6

**Comment by notgull** [comment]
Rebased on the newest master

**Comment by notgull** [comment]
The main caveat is that the `OwnedDisplayHandle` change wasn't accepted into `winit`, so the `DisplayBuilder` function is now `unsafe`.

**Comment by emilk** [comment]
Any chance for a glutin release with `raw-window-handle` 0.6? 🙏

**Comment by kchibisov** [comment]
I'm not sure how soon, since I don't have time to review the glutin stuff now. it's not like you can't use it at all if you have only raw-window-handle 0.6, since you can convert 0.6 to 0.5 and e.g. winit provides all 3 of them at the same time, so you can pick 0.5 for glutin and 0.6 for other winit stuff.

But it'll be review/merge within a month...

**Comment by emilk** [comment]
Ah, winit supports all three of them at the same time, I didn't realize that (thought I had to pick one). Then I can probably figure something out. Thanks for the pointer!

**Comment by MarijnS95** [comment]
@emilk what makes you juggle multiple versions, instead of locking winit to 0.5 and using that in glutin?

**Comment by emilk** [comment]
[`eframe`](https://crates.io/crates/eframe) has to support both `glutin` (locked at 0.5) and `wgpu` (locked at 0.6).

**Comment by MarijnS95** [comment]
Right, that is indeed a painful situation.

**Comment by notgull** [comment]
Don't really feel like rebasing this and it's unlikely to be reviewed, so I'll abandon this in favor of #1670

**Comment by kchibisov** [comment]
It'll be though, but there's a big chance that I write parts myself. Like I'd like to use safe handles myself, it's just winit is lacking and I said it to you before. Forcing everyone to just start `Arc` everything sounds a bit wasteful.

**Pull request closed without merging**
