### PR TITLE
Upgrade `winit` 0.29.2 → 0.30.0

### PR DESCRIPTION
**Pull request by ErichDonGubler**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality: I've updated examples, which I think might be sufficient?

Resolves https://github.com/rust-windowing/glutin/issues/1674.

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
This is a less-complete version of #1675, but in trying to understand the upgrade path for [WGPU](https://github.com/gfx-rs/wgpu)'s, I decided to tackle my own version of this. I don't expect this to be merged over that one; mostly curious if the efforts I took to make incremental changes might be easier to review/interesting to base that PR on top of instead (assuming the mistakes I'm sure I've made are tolerable). If not, no worries! 🙂

**Comment by MarijnS95** [comment]
The changes in `glutin-winit`'s `lib.rs` look identical to #1675 minus some `GlutinEventLoop` trait to support the older `EventLoop` as argument to `create_display()`.

Both PRs are refactoring the examples in a completely different way though, and I lean towards what you're doing here by loosing less code and maintaining more of the original architecture. But it remains hard to review both PRs as they (inevitably) move a lot of code around in the diff.

**Comment by ErichDonGubler** [comment]
@MarijnS95: I strongly recommend going through these changes commit-by-commit, rather than looking through the overall diff. I've striven to make each as small as possible.

**Comment by MarijnS95** [comment]
@ErichDonGubler since you already expressed that you didn't expect this PR to get merged in favour of the other one, I didn't give this PR (nor the other one) more than a quick scroll-through.

Since your PR history is nice and readable, I propose to integrate that in one of the two branches.

**Comment by marc2332** [comment]
@ErichDonGubler Do you want me to just copy your examples straight into my PR or do you want to maybe rebase this PR on mine with my core changes and your examples so we can change it merge it into mine?

**Comment by ErichDonGubler** [comment]
Alright, after the most recent force-pushing to make sure my a rebase of _just_ my changes still worked as expected, I added…

* …some autosquash-able commits (e176e81, 2b26e26, 854d8af, fa1d41a) for reconciliation of minor details b/w this and #1675. These add some `Co-Authored-By: …` tags for the appropriate contributions from @marc2332 and @MarijnS95, as best as I could determine original authorship.
* …a new commit (5f1a241) I've marked as authored by @marc2332 containing their changes for the `GlutinEventLoop` trait. 

I'll be auto-squashing these changes down momentarily.

**Comment by ErichDonGubler** [comment]
@marc2332: I'll leave the choice up to you whether you want to force-push this branch's history onto yours at #1675, or just abandon it and get a fresh round of @MarijnS95's feedback here. I'm willing to handle feedback if it's left open here, in case that helps. 🙂

**Review by kchibisov — APPROVED** [review]
I've Incorporated all the changes from #1675 and applied some minor style/doc fixes.

**Comment by marc2332** [comment]
> I've Incorporated all the changes from #1675 and applied some minor style/doc fixes.

Not sure why you did that, I already had his changes in my PR 🤔

**Pull request merged**
